# Xiaotian Tian's Notes on Numpy basics

Learned from:
- https://numpy.org/doc/stable/user/quickstart.html
- https://cs231n.github.io/python-numpy-tutorial/#numpy

## Arrays

A **numpy array** is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

### Array Basics

In [24]:
import numpy as np

# initialise
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [25]:
# shape indicates the size of the array in each dimension
a.shape

(3, 3)

In [26]:
# we can index into the array
a[0]
a[0][0]

1

In [27]:
# ndim if the rank
a.ndim

2

In [28]:
# type of the array object
type(a)

numpy.ndarray

### Array Creation

In [29]:
# create array from list
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [30]:
# create array of all zeros
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# create array of all ones
c = np.ones((1,4))
c

array([[1., 1., 1., 1.]])

In [32]:
# create array of a specific constant
d = np.full((3,2), 0.4)
d

array([[0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4]])

In [33]:
# create identity matrix
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# create random array
f = np.random.random((3,3))
f

array([[0.46685919, 0.82923005, 0.60544234],
       [0.29074676, 0.93786349, 0.73287407],
       [0.32651866, 0.45784459, 0.88733675]])