# Xiaotian Tian's Notes on Numpy basics

Learned from:
- https://numpy.org/doc/stable/user/quickstart.html
- https://cs231n.github.io/python-numpy-tutorial/#numpy

## Arrays

A **numpy array** is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

### Array Basics

In [22]:
%%time

import numpy as np

# initialise
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3]])
a

CPU times: user 139 µs, sys: 894 µs, total: 1.03 ms
Wall time: 3.56 ms


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [23]:
# shape indicates the size of the array in each dimension
a.shape

(3, 3)

In [24]:
# we can index into the array
a[0]
a[0][0]

1

In [25]:
# ndim if the rank
a.ndim

2

In [26]:
# type of the array object
type(a)

numpy.ndarray

### Array Creation

In [27]:
# create array from list
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [28]:
# create array of all zeros
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# create array of all ones
c = np.ones((1,4))
c

array([[1., 1., 1., 1.]])

In [30]:
# create array of a specific constant
d = np.full((3,2), 0.4)
d

array([[0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4]])

In [31]:
# create identity matrix
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# create random array
f = np.random.random((3,3))
f

array([[0.47202293, 0.217272  , 0.80471493],
       [0.46707059, 0.70314249, 0.27358966],
       [0.53886697, 0.74171347, 0.77333479]])

In [35]:
# arange: analogous to the Python build-in range, but returns an array
g = np.arange(10, 30, 5)
print(g)

# we can also reshape after arange
h = np.arange(0, 12).reshape(3, 4)
print(h)

[10 15 20 25]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
%reset

Nothing done.


### Array Indexing and Slicing

#### Slicing Indexing and Integer Indexing

In [13]:
%%time

# reimport numpy
import numpy as np

# create a sample array
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

CPU times: user 32 µs, sys: 55 µs, total: 87 µs
Wall time: 94.9 µs


In [14]:
# slicing
# Use slicing to pull out the subarray consisting of:
    # the first 2 rows
    # and columns 3 and 4
# produces array of shape (2, 2):
a[:2, 2:4]

array([[3, 4],
       [7, 8]])

Slicing only creates a view of the original array, not a copy, so modifying the slice also modifies the original array:

In [15]:
b = a[:2, :2]
b[0, 0] = 114514
a

array([[114514,      2,      3,      4],
       [     5,      6,      7,      8],
       [     9,     10,     11,     12]])

While **slicing indexing** creates a view, any use of **integer indexing** will create an array of lower rank:

In [16]:
c = np.array([
    [1, 1, 2, 3],
    [1, 234, 21, 2],
    [21, 2, 1, 3]
])

# purely slicing indexing
d = c[:1, :]
print(d)
d.shape

[[1 1 2 3]]


(1, 4)

In [17]:
# any integer indexing yields an array of a lower rank
e = c[0, :]
print(e)
e.shape

[1 1 2 3]


(4,)

Same distinction, but apply to columns (note that a single column will be transposed to a row):

In [18]:
f = c[:, 0]
print(f)
f.shape

[ 1  1 21]


(3,)

In [19]:
g = c[:, :1]
print(g)
g.shape

[[ 1]
 [ 1]
 [21]]


(3, 1)

When you index into numpy arrays using *slicing*, the resulting array view will always be a *subarray of the original array*.
In contrast, *integer array indexing* allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [20]:
h = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

# an example of integer array indexing instead of slicing
g = h[[0, 2, 3], [0, 1, 0]]
print(g)

# this is equivalent to:
k = np.array([h[0,0], h[2,1], h[3,0]])
print(k)

[1 6 7]
[1 6 7]


One useful trick with integer array indexing is selecting or mutating one element from *each row* of a matrix.

In [21]:
l = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# indices array
m = np.array([0, 0, 0, 1])

# mutate the original array
# Mutate one element from each row of a using the indices in m:
l[np.arange(4), m] += 10  # np.arange(4) yields array([0, 1, 2, 3])
l

array([[11,  2,  3],
       [14,  5,  6],
       [17,  8,  9],
       [10, 21, 12]])

In [22]:
%reset

Nothing done.


#### Boolean Indexing

We can use **boolean indexing** to convert an array to an array consists of boolean values, or filtering out all the element in an array that satisfies a boolean expression.

In [23]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# array converted to boolean array
bool_idx = (a > 2)

bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [24]:
# create a rank 1 array 
# which consists of all of the elements
# that satisfies a boolean expression:
print(a[a > 2])

[3 4 5 6]


In [25]:
%reset

Nothing done.


## Datatypes

Every numpy array is a grid of elements of *the same type*.
Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [27]:
import numpy as np

# int64
a = np.array([
    [1, 2],
    [3, 4]
])
print(a.dtype) # int64

# float64
b = np.array([
    [1.0, 2.0],
    [3.0, 4.0]
])
print(b.dtype) # float64

# force a specific datatype
c = np.array([
    [1, 2],
    [3, 4]
],
dtype = np.float64
)
print(c.dtype) # float64

int64
float64
float64


In [28]:
%reset

Nothing done.


## Array Maths

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

### Elementwise Maths

In [1]:
import numpy as np

# init
x = np.array([
    [1, 2],
    [3, 4]
])
y = np.array([
    [5, 6],
    [7, 8]
])

In [2]:
# sum
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [3]:
# subtract
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [5]:
# elementwise product
# NOT MATRIX PRODUCT!!!
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [6]:
# elementwise summation
print(x - y)
print(np.divide(x, y))

[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# elementwise squareroot
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [10]:
%reset

Nothing done.


### Vector and Matrix Product

In [37]:
import numpy as np

# init
x = np.array([
    [1, 2],
    [3, 4]
])
y = np.array([
    [5, 6],
    [7, 8]
])

v = np.array([9, 10])
w = np.array([11, 12])

In [38]:
# inner/dot product of vectors
print(v @ w)
print(v.dot(w))
print(np.dot(v, w))

219
219
219


In [39]:
# matrix vector product
print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]
[29 67]


In [40]:
# matrix matrix product
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Other Maths

In [43]:
z = np.array([
    [1, 2],
    [3, 4]
])

# summations

# sum of all elements
print(np.sum(z))
print(z.sum())

# sum by column
print(np.sum(z, axis=0))
print(z.sum(axis=0))

# sum by row
print(np.sum(z, axis=1))
print(z.sum(axis=1))

10
10
[4 6]
[4 6]
[3 7]
[3 7]


In [7]:
# transpose
print(z.T)

# but note that we cannot transpose rank 1 array
print(v.T)

[[1 3]
 [2 4]]
[ 9 10]


In [8]:
%reset

## Broadcasting

**Broadcasting** is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [15]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
v = np.array([1, 0, 1])

# Add the vector v to each row of the matrix x with an explicit loop
x1 = np.copy(x)
for i in range(4):
    x1[i, :] += v
print(x1)


# Doing the same using broadcasting
x2 = np.copy(x)
x2 += v
print(x2)

%reset

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Nothing done.


The line `y = x + v` works even though `x` has shape (4, 3) and `v` has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be **compatible** in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or [this explanation](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc).

Functions that support broadcasting are known as **universal functions**. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [21]:
import numpy as np

# init
v = np.array([1, 2, 3]) # shape (3,)
w = np.array([4, 5]) # shape (2,)
x = np.array([
    [1, 1, 4],
    [5, 1, 4]
])

# cross/outer product
print(np.reshape(v, (3, 1)) * w)

# add a vector to each row of a matrix
print(x + v)

# add a vector to each column of a matrix
print((x.T + w).T)
# another solution
print(np.reshape(w, (2, 1)) + x)

# multiply a matrix by a constant
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 3 7]
 [6 3 7]]
[[ 5  5  8]
 [10  6  9]]
[[ 5  5  8]
 [10  6  9]]
[[ 2  2  8]
 [10  2  8]]


In [45]:
%reset

Nothing done.


## Others

### reshape and resize

The `reshape` function returns its argument with a modified shape, whereas the `ndarray.resize` method modifies the array itself (and takes a touple of shape as argument):

In [50]:
import numpy as np

# reshape
a = np.arange(12).reshape(3, 4)
b = a.reshape(2, -1) # if a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
print(a)
print(b)

# resize
a.resize((1, 12))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [51]:
%reset

Nothing done.


### Stacking together different arrays

Arrays ca be **stacked together** along different axes:

In [3]:
import numpy as np

a = np.random.random((2, 2))
b = np.ones((2, 2))

print(a)
print(b)

# vstack
c = np.vstack((a, b))
print(c)

# hstack
d = np.hstack((a, b))
print(d)

[[0.18743575 0.2193718 ]
 [0.98845463 0.82421983]]
[[1. 1.]
 [1. 1.]]
[[0.18743575 0.2193718 ]
 [0.98845463 0.82421983]
 [1.         1.        ]
 [1.         1.        ]]
[[0.18743575 0.2193718  1.         1.        ]
 [0.98845463 0.82421983 1.         1.        ]]


The function `column_stack` stacks 1D arrays *as columns* into a 2D array. It is equivalent to `hstack` *only* for 2D arrays:

In [9]:
v = np.arange(4)
w = np.arange(2, 6)
print(f"v: {v}")
print(f"w: {w}")

# for 1D arrays, it's different from hstack
# column_stack
e = np.column_stack((v, w))
print(e)
# hstack
f = np.hstack((v, w))
print(f)

# for 2D arrayes, they are the same
g = np.column_stack((a, b))
print(g)
h = np.hstack((a, b))
print(h)


v: [0 1 2 3]
w: [2 3 4 5]
[[0 2]
 [1 3]
 [2 4]
 [3 5]]
[0 1 2 3 2 3 4 5]
[[0.18743575 0.2193718  1.         1.        ]
 [0.98845463 0.82421983 1.         1.        ]]
[[0.18743575 0.2193718  1.         1.        ]
 [0.98845463 0.82421983 1.         1.        ]]


On the other hand, the function `row_stack` is equivalent to `vstack` for any input arrays. In fact, row_stack is an alias for vstack.

In complex cases, `r_` and `c_` are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals `:`.

In [10]:
np.r_[1:4, 12, 13]

array([ 1,  2,  3, 12, 13])

In [12]:
np.c_[np.array([1, 1, 4]), np.array([5, 1, 4])]

array([[1, 5],
       [1, 1],
       [4, 4]])

When used with arrays as arguments, `r_` and `c_` are similar to `vstack` and `hstack` in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.

In [13]:
%reset

Nothing done.


### Splitting one array into several smaller ones